---
- name: Install BMI
  hosts: bmi

  tasks:
  - name: Copy BMI installation file to BMI server
    become_user: root
    become: yes
    copy:
      src: ../containers/bmi
      dest: /home

  - name: Build the BMI image
    become_user: root
    become: yes
    docker_image:
      path: /home/bmi/
      name: bmi
      tag: latest
      push: no

  - name: Create directory for ceph volume and copy ceph keyring there
    become_user: root
    become: yes
    copy: 
      src: "{{ item }}"
      dest: /etc/ceph/
    with_fileglob:
      - ../ceph_keyring/*
  
  - name: Run BMI container
    become: yes
    docker_container:
      name: bmi_image
      image: bmi
      state: started
      pull: no
      interactive: yes
      tty: yes
      ports:
      - "3260:3260"
      - "7000:7000"
      - "9000:9000"
      - "9893:9893"
      volumes: "/etc/ceph:/etc/ceph"
...

