---
- hosts: ansible2
  sudo: yes
  tasks:
 
  - name: install git and docker on ansible2
    yum: name={{ item }} state=present
    with_items:
    - docker 
    - epel-release
    - docker-io
    - git

  - name: remove /var/lib/docker
    file:
      path: /var/lib/docker
      state: absent

  - name: duplicate file docker to docker.org
    become: yes
    become_user: root 
    copy:
      src: /etc/sysconfig/docker
      dest: /etc/sysconfig/docker.org

  - name: change file /etc/sysconfig/docker
    command: sed -i 's/--selinux-enabled //' /etc/sysconfig/docker

  - name: change file /etc/sysconfig/docker
    command: sed -i 's/# setsebool -P docker_transition_unconfined 1/setsebool -P docker_transition_unconfined 1/' /etc/sysconfig/docker

  - name: restart server
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    become: true
    ignore_errors: true


  - name: waiting for the server to come back
    local_action: wait_for host=testcentos state=started delay=10 timeout=30
    sudo: false

  - name: start docker server
    command: systemctl start docker
  
  - name: enable docker when boot
    command: systemctl enable docker

...
