- hosts: hil
  tasks:

#    - name: create directory 
#      file:
#        path: /home/centos/bolted
#        state: directory
   
#    - name: pull bolted repo from github
#      become: yes
#      become_user: root
#      git:
#        repo: https://github.com/BU-NU-CLOUD-SP18/Secure-Cloud-Automated-Deployment.git
#        dest: /home/centos/bolted
#        clone: yes

    - name: copy hil installation file to remote vm
      become: yes
      become_user: root
      copy:
        src: ../containers/hil
        dest: /home/
 
##################################
# Hil database server  deployemnt 
##################################
 
#    - name: build hil database image from docker hub
#      become: yes
#      become_user: root
#      command: docker build --rm -t hil_postgres:latest .   
#      args:
#        chdir: /home/centos/bolted/containers/hil/postgres_docker

    - name: build hil databse image from docker hub postgres image
      become: yes
      bcomee_user: root
      docker_image:
        name: hil_postgres
        tag: latest
        path: /home/hil/postgres_docker
        push: no

#    - name: run postgres hil database image 
#      become: yes
#      become_user: root
#      command: docker run -itd --name hil_database hil_postgres:latest
#      args:
#        chdir: /home/centos/bolted/containers/hil/postgres_docker

    - name: run hil postgres database container
      become: yes
      become_user: root
      docker_container:
        name: hil_database
        image: hil_postgres:latest
        state: started
        pull: no
        interactive: yes
        tty: yes
        detach: yes

##################################
# Hil server deployment
##################################

    - name: store the postgresql database ip to variable
      become: yes
      become_user: root
      command: docker inspect --format \{\{.NetworkSettings.IPAddress\}\} hil_database
      register: output

    - name: display postgresql database ip address
      debug: 
        msg: "The ip address of hil database is {{ output.stdout }}"

#   - name: create centos apache httpd image
#     become: yes
#     become_user: root
#     command: docker build --rm -t httpd:latest .
#     args:
#       chdir: /home/httpd/

#   - name: pull hil network server image
#     become: yes 
#     become_user: root
#     docker_image:
#       name: leonjia0112/hil_apache:latest

#    - name: modify the hil.cfg file with updated 
#      command: /bin/bash database_ip.sh {{ output.stdout }}
#      args:
#        chdir: /home/centos/bolted/containers/hil/

#    - name: build hil apache server docker file
#      become: yes
#      become_user: root
#      command: docker build --rm -t  hil_apache:latest .
#      args:
#        chdir: /home/hil/apache_docker_prebuild

    - name: build hil apache server docker file
      become: yes
      become_user: root
      docker_image:
        path: /home/hil/apache_docker_prebuild
        name: hil_apache_pre
        tag: latest
        push: no
        buildargs:
          DATABASE_IP: {{ output.stdout }}

#    - name: run hil apache server contain
#      become: yes
#      beomce_user: root
#      command: docker run -itd --name hil_server hil_apache:latest  

    - name: run hil apache server contaiener
      become: yes
      become_user: root
      docker_container:
        name: hil_server
        image: hil_apache_pre:latest
        state: started
        pull: no
        interactive: yes
        tty: yes
        detach: yes
        
