---
- hosts: keylime-cv
  tasks:

    - name: clone repo to directory
      become: yes
      become_user: root
      git:
        repo: https://github.com/leonjia0112/bolted.git
        dest: /home/bolted
        clone: yes

    - name: build my_keylime docker image
      command: docker build -t keylime /home/bolted/containers/keylime

    - name: update host ip address in keylime configuration file
      become: yes
      become_user: root
      command: ./ip_setup.sh {{ inventory_hostname }}
      args:
        chdir: /home/bolted/containers/keylime

    - name: run keylime container with registrar and verifier
      command: docker run -it --name keylime_cv -p 8881:8881 -p 8890:8890 -p 8891:8891 -8990:8990 -p 8991:8991 -p 8992:8992 my_keylime:latest bash "run.sh" 
        chdir: /home/boltd/containers/keylime

    - name: print message
      debug:
        msg:  "finished {{ inventory_hostname }}"

- hosts: keylime-client
  tasks:

    - name: clone repo to directory
      become: yes
      become_user: root
      git:
	repo: https://github.com/leonjia0112/bolted.git
        dest: /home/bolted
        clone: yes

    - name: build my_keylime docker image
      command: docker build -t keylime /home/bolted/containers/keylime

    - name: update host ip address in keylime configuration file
      become: yes
      become_user: root
      command: ./ip_setup.sh {{ inventory_hostname }}
      args:
	chdir: /home/bolted/containers/keylime

    - name: run keylime client node
      command: docker run -it -p 9002:9002 keylime:latest bash '-c' "init_tpm_server; tpm_serverd; python ../keylime/cloud_node.py"
      args:
        chdir: /home/bolted/containers/keylime
...


